import os 
os.system("cls")

primeiro_numero = int(input("Digite o primeiro numero: "))
segundo_numero = int(input("Digite o segundo numero: "))

soma = primeiro_numero + segundo_numero:
    profuto = primeiro_numero * segundo_numero
if primeiro_numero > segundo_numero: 
     maior = primeiro_numero
     menor = segundo_numero 
else: 
    maior = segundo_numero
    menor + primeiro_numero 
    
print(f"Sima: {soma}")
print(f"Produto: {produto}")
print(f"Maior númro: {maior}")
print(f"Menor número: {menor}")
        
